name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install pytest explicitly
        pip install pytest
        # Install your package and its dependencies
        pip install -r requirements.txt
        pip install -e .
        # List installed packages to verify pytest installation
        pip list

    - name: Download NLTK resources
      run: |
        python -c "import nltk; nltk.download('punkt')"
        python -c "import nltk; nltk.download('punkt_tab')"
 
    - name: Run tests
      run: |
        # Use python -m to ensure we're using the correct Python environment
        python -m pytest tests/